name: GitHub scheduled action
on:
  schedule:
    - cron: '*/30 6-22 * * *'
jobs:
  Log-something:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Log-something-step
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
